### ISSUE TITLE
入力デバイスプラグイン版使用時に原因不明の画面が表示される

### ISSUE THREAD

**Issue by winup-zhou** [automatic9045/AtsEX#22]
**開発環境**

- Bve TrainSim 6.0.7554.619
- AtsEX バージョン 1.0.31106.1
- .NET Framework 4.8

このプラグイン (https://github.com/winup-zhou/TGMT-CBTC-EX/commit/6ecaa10e7649d637f2fd92b906ead25ac86f24bf) はDXDynamicTecture機能を使用します。

プラグインが読み込みされると、この画面が**二度**表示され、**DXDynamicTecture描画置換に使用するファイル名**が表示されます。

![0cdcd65906706bbb298bebc65c868f2f](https://github.com/automatic9045/AtsEX/assets/60384089/4b6debe0-ceec-439d-b78e-455c9b2321d3)

**問題の再現手順**

1. AtsEX、車両およびマッププラグインの適切なインストール
2. Visual Studioに表示されるメモリの状況を監視するためのマップを読み込みます。
3. 車両ファイルの読み込み開始時にこの画面が表示され、読み込みが中断されます。
4. 確認をクリックすると読み込みが続行され、それ以降の機能は正常に動作する。

この問題はATSプラグイン版では発生しません。

**Comment by automatic9045** [comment]
デバッグ用に表示させていたメッセージボックスを削除し忘れていたのが原因でした。

[ver1.0-RC2](https://github.com/automatic9045/AtsEX/releases/tag/v1.0.31118.1) にて修正しました。ご報告ありがとうございました！

**Comment by winup-zhou** [comment]
ありがとう。

私のNuGet package managerにはまだ v1.0-RC3 バージョンはリストされていません...
アップデートされましたか？

**Comment by automatic9045** [comment]
先ほどアップしました！
NuGet から参照しているパッケージが ver1.0-RC1 であっても、実際に動作するのは AtsEX 本体に同梱している DLL ですので問題は解消されます。
