### ISSUE TITLE
「シナリオを開く」を繰り返すと例外が発生する

### ISSUE THREAD

**Issue by yusuke1109** [automatic9045/AtsEX#36]
Bve (5.8.7554.391 or 6.0.7554.619) + AtsEX v1.0.40401.1（入力デバイスプラグイン版）において，「シナリオを開く」→任意のサンプルシナリオを選択→シナリオ読み込み完了後「シナリオを閉じる」を10回ほど繰り返すと以下の例外が発生します．
![image](https://github.com/automatic9045/AtsEX/assets/38825122/77f7b6b1-9e56-45c7-88a6-ea812d0765f8)
その後，OKを選択するとBVE本体のエラー確認画面が表示され，続行を選択するとシナリオが読み込まれますが，状態ウインドウが表示できなくなります．
![image](https://github.com/automatic9045/AtsEX/assets/38825122/b4821dce-fd4f-447b-91ac-5755b5988d53)

**Comment by automatic9045** [comment]
ご報告ありがとうございます。確認しましたところ、AtsEX コア拡張機能の ContextMenuHacker に不具合が見つかりました。  
配布版に反映されるのは次版になりますが、修正するコミットをプッシュ次第こちらのスレッドにも追記させていただきます。

**Comment by automatic9045** [comment]
コミット 633dbce0bd2eb3873abcad489e8d6aa0482a7129 にて修正しました。ありがとうございました🙇‍♂️
