### ISSUE TITLE
特定のサンプルシナリオを順に開くと例外が発生する

### ISSUE THREAD

**Issue by yusuke1109** [automatic9045/AtsEX#37]
Bve (5.8.7554.391 or 6.0.7554.619) + AtsEX v1.0.40401.1（入力デバイスプラグイン版）において，「独自マップ構文サンプル」→「スプリクトプラグインサンプル」の順でサンプルシナリオを開くと以下の例外が発生します．
![image](https://github.com/automatic9045/AtsEX/assets/38825122/4f8061d6-ce6b-4183-a080-540102a14d65)
- なお，「拡張地上子サンプル」→「独自マップ構文サンプル」→「スプリクトプラグインサンプル」の順で開くと発生しないようです．

**Comment by automatic9045** [comment]
ご報告ありがとうございます。確認しましたところ、独自マップ構文サンプルに同梱されている TrainController.dll がイベントメモリリークのバグを含む β0.17.6 版のままとなっていました。

![image](https://github.com/automatic9045/AtsEX/assets/67314487/ff11d0ae-ba74-435d-9912-339142c86ad1)

配布版に反映されるのは次版になりますが、修正するコミットをプッシュ次第こちらのスレッドにも追記させていただきます。

**Comment by automatic9045** [comment]
コミット e4386218a7d3ec499129a72b8f9510b70f2865c9 にて修正しました。ありがとうございました！
